# Generated by prepare.py; edit the original explorer or browser adapters.
options(shiny.maxRequestSize = 50 * 1024^2)
library(shiny)
library(ggplot2)
library(plotly)
source("R/data.R", local = TRUE)
source("R/plot.R", local = TRUE)
source("R/pairing.R", local = TRUE)
source("R/pairing_module.R", local = TRUE)
source("R/auc.R", local = TRUE)
source("R/auc_module.R", local = TRUE)
source("R/browser_data.R", local = TRUE)
source("R/browser_plots.R", local = TRUE)
paired_trend_plot <- browser_paired_plot(paired_trend_plot)
pairing_cutoff <- as.Date("2026-09-01")
group_choices <- c("Genotype" = "genotype", "Strain" = "strain", "Bacterial diet" = "bacteria", "Culture temperature" = "culture", "Configuration" = "config", "Source" = "source", "Synchronization" = "sync")
facet_choices <- c("Pooled view" = "none", "By experiment / date" = "run_id", "By date" = "date", "By culture temperature" = "culture", "By bacterial diet" = "bacteria", "By configuration" = "config", "By source" = "source")

ui <- function(request) {
  initial <- empty_browser_snapshot()
  all_data <- initial$data
  choices_for <- function(field) sort(unique(as.character(all_data[[field]])))
  multi <- function(id, label, selected = NULL) selectizeInput(id, label, choices_for(id), selected = selected, multiple = TRUE,
    options = list(placeholder = "All — type to filter", plugins = list("remove_button"), maxOptions = 1000))
  date_limits <- browser_dates(all_data)
  htmltools::attachDependencies(fluidPage(
    tags$head(tags$title("Thermotolerance Explorer"),
      
      tags$link(rel = "stylesheet", href = "style.css"), tags$script(src = "browser.js")),
    div(class = "topbar", div(div(class = "eyebrow", "THERMO / DATA WORKSPACE"), h1("Thermotolerance explorer"),
      p("Follow the curve. Find the experiment behind it.")), span(class = "local-badge", "BROWSER · LOCAL FILES")),
    div(class = "card file-card",
      h2("Open your data"),
      p("Select CSV files from this computer. They are processed in this browser, not uploaded to GitHub. Refreshing the page clears the session; select your files again."),
      div(class = "file-grid",
        div(fileInput("csv_SKKU", "SKKU CSV", accept = ".csv", buttonLabel = "Choose CSV"), actionButton("remove_SKKU", "Remove SKKU")),
        div(fileInput("csv_JHU", "JHU legacy CSV (optional)", accept = ".csv", buttonLabel = "Choose CSV"), actionButton("remove_JHU", "Remove JHU"))),
      textOutput("file_status"),
      p(class = "hint", "Selecting a replacement resets filters and manual exclusions. To update data, choose the newer CSV. Files are not saved by the app.")),
    conditionalPanel("output.has_data", div(class = "workspace",
      div(class = "filters",
        div(class = "section-title", "Build a comparison"),
        checkboxInput("compare_periods", "Compare time periods", FALSE),
        conditionalPanel("input.compare_periods",
          selectInput("period_count", "Number of time periods", choices = c(2, 3, 4), selected = 2),
          dateInput("period_cutoff", "First cutoff", value = "2026-07-01"),
          conditionalPanel("input.period_count >= 3", dateInput("period_cutoff2", "Second cutoff", value = "2026-08-01")),
          conditionalPanel("input.period_count >= 4", dateInput("period_cutoff3", "Third cutoff", value = "2026-09-01")),
          p(class = "hint", "Cutoffs must increase. Each cutoff starts the next period; dates before the first and after the last remain included.")),
        checkboxGroupInput("sources", "Data sources", c("SKKU · 2024–2026" = "SKKU", "JHU · legacy" = "JHU"), selected = "SKKU"),
        multi("genotype", "Genotype", c("wild type", "sma-9(wk55)")), multi("strain", "Strain"),
        multi("culture", "Culture temperature", "20°C"), multi("bacteria", "Bacterial diet", "OP50-1"),
        multi("config", "Experimental configuration", "standard"), multi("sync", "Synchronization"),
        tags$details(tags$summary("Dates, hours & experiments"),
          dateRangeInput("dates", "Assay dates", start = date_limits[1], end = date_limits[2], min = date_limits[1], max = date_limits[2]),
          checkboxInput("undated", "Include undated observations", FALSE),
          sliderInput("hours", "Heat exposure (hours)", min = 0, max = 4, value = c(0, 4), step = 0.5),
          selectizeInput("runs", "Recorded runs", choices = NULL, multiple = TRUE, options = list(placeholder = "All recorded runs"))),
        checkboxInput("quality", "Apply existing analysis exclusions", TRUE),
        p(class = "hint", "Blank optional filters mean all. Filters combine by intersection. JHU legacy: OP50 diet; standard configuration and synchronization. Select both OP50 and OP50-1 to include both diets."),
        div(class = "button-row", actionButton("defaults", "Example comparison"), actionButton("clear", "Clear filters")),
        hr(), div(class = "section-title", "Keep this view"),
        downloadButton("save_view", "Save view (.json)"),
        fileInput("restore_view", "Restore a saved view", accept = ".json"),
        
        textOutput("loaded_at")),
      div(class = "main-content",
        uiOutput("metrics"),
        div(class = "card",
          div(class = "card-heading", h2("Survival curves"), span(class = "hint", "Hover to inspect · click a point for details · drag to zoom")),
          div(class = "plot-controls",
            selectInput("group", "Color / compare", group_choices, selected = "genotype"),
            selectInput("facet", "Arrange panels", facet_choices),
            selectInput("mode", "Display", c("Mean curves" = "mean", "Means + observations" = "points", "Plate curves" = "replicates", "Means + plate curves" = "both"), selected = "points"),
            selectInput("unit", "Mean weighting", c("Equal observations (existing method)" = "plate", "Equal recorded runs" = "run")),
            selectInput("uncertainty", "Error bars", c("Standard error" = "se", "Standard deviation" = "sd", "None" = "none"))),
          uiOutput("data_notice"),
          div(class = "panel-pagination", numericInput("panel_page", "Panel page (12 per page)", 1, min = 1, step = 1), textOutput("panel_count")),
          uiOutput("curve_container"),
          div(class = "export-bar", downloadButton("plot_pdf", "Figure PDF"), downloadButton("plot_png", "Figure PNG"), downloadButton("export_rows", "Selected data CSV"), downloadButton("export_summary", "Summary CSV")),
          p(class = "hint", "Figure exports use the displayed panel page. CSV exports contain all selected panels. Error bars are clipped at 0–100%; exact values are in Summary.")),
        auc_ui("auc"),
        paired_date_ui("paired", pairing_cutoff),
        div(class = "card detail-card", tabsetPanel(id = "detail_tab",
          tabPanel("Point inspector", uiOutput("point_detail"),
            div(class = "button-row", actionButton("exclude_point", "Exclude selected observation"), actionButton("clear_exclusions", "Clear manual exclusions")),
            textOutput("excluded_count"), tableOutput("plate_detail")),
          tabPanel("Observations", div(class = "table-controls", textInput("row_search", "Search selected rows", placeholder = "Strain, date, note, experiment…"), numericInput("row_page", "Page (25 rows)", 1, min = 1, step = 1)), textOutput("row_count"), tableOutput("rows")),
          tabPanel("Summary", tableOutput("summary_table"), p(class = "hint", "First 100 rows shown. Download Summary CSV for the complete table.")),
          tabPanel("Methods & provenance",
            h3("What the curves mean"),
            p("Survival = 100 × alive / (alive + dead). Ruptured, suicide and missing counts are retained for inspection but excluded from this denominator, matching the existing plotting code. Lines join observed times; they are not fitted survival models."),
            p("The default mean gives each recorded observation equal weight at each time. SE = SD / √n. Equal recorded runs first averages observations within each source/date/experiment, then averages those run means. A run identifier does not establish biological independence. One unit has undefined SD/SE and no error bar."),
            h3("Default exclusions"),
            p("All sources: total across all five count categories must be at least 15. SKKU: exclude the exact note ‘10 total’. JHU: exclude IW938cuz_4G, notes matching room_temp_high_setup, donotuse, odd_result_all or special_N2, and temperature-shift strain annotations. The checkbox controls these rules; invalid or negative/non-integer counts, invalid times and zero denominators are always omitted."),
            h3("Labels and replicate identity"),
            p("SKKU diet labels follow the existing import convention: raw OP50 → OP50-1 and raw plain → OP50. CB1370-SNU → CB1370. Strain suffixes after a space are removed for display. JHU culture and two genotype spellings are normalized as in the existing loader. All original labels remain in raw_* export columns. Lab-confirmed JHU metadata: bacterial diet OP50, configuration standard, and synchronization standard; these annotations apply to all JHU observations. Missing source values remain ‘Not recorded’ in raw_* columns. N2, N2.therm and N2.thaw remain distinct strains."),
            p("A candidate plate is source + date + experiment + row + raw strain + culture + diet + configuration + synchronization. Missing date/experiment/row or repeated time points make that plate identity unresolved. Those observations remain in summaries, but are not connected into plate curves or counted as resolved plates. No duplicates are silently removed."),
            h3("Reproducibility"),
            p("Source CSVs are selected locally and read when chosen. Choose a newer file to update; refreshing the page clears loaded data. Saved views contain filters, manual exclusions, plotting settings and source MD5 fingerprints. Reopening a view warns if the data changed; a view does not contain a data snapshot. Download Selected data CSV to preserve the included observations. This explorer performs descriptive analysis; it does not calculate significance tests."),
            verbatimTextOutput("provenance")))))
    ),
    ),
    div(class = "footer", "THERMOTOLERANCE EXPLORER", span("Local data · traceable observations · reproducible views"))
  ), htmltools::findDependencies(htmltools::as.tags(plotly::plot_ly(x = numeric(), y = numeric(), type = "scatter", mode = "markers"))), append = TRUE)

}

server <- function(input, output, session) {
  initial <- empty_browser_snapshot()
  dataset <- reactiveVal(initial)
  excluded <- reactiveVal(character())
  selected <- reactiveVal(NULL)
  updateSelectizeInput(session, "runs", choices = sort(unique(initial$data$run_id)), server = TRUE)
  settings <- reactive({
    req(input$dates, input$hours)
    period_count <- as.integer(input$period_count %||% 2)
    validate(need(length(period_count) == 1 && period_count %in% 2:4, "Choose two, three or four periods."))
    cutoffs <- c(as.character(input$period_cutoff %||% "2026-07-01"),
      as.character(input$period_cutoff2 %||% "2026-08-01"), as.character(input$period_cutoff3 %||% "2026-09-01"))[seq_len(period_count - 1L)]
    list(sources = input$sources, genotype = input$genotype, strain = input$strain,
      culture = input$culture, bacteria = input$bacteria, config = input$config, sync = input$sync,
      dates = as.character(input$dates), hours = input$hours, runs = input$runs, undated = input$undated,
      quality = input$quality, excluded = excluded(), group = input$group, facet = input$facet,
      mode = input$mode, unit = input$unit, uncertainty = input$uncertainty, panel_page = input$panel_page,
      compare_periods = isTRUE(input$compare_periods), period_cutoff = cutoffs[1],
      period_count = period_count, period_cutoffs = cutoffs)
  })
  filtered <- reactive({
    req(nrow(dataset()$data) > 0)
    s <- settings()
    if (s$compare_periods) {
      valid <- tryCatch({validate_period_cutoffs(s$period_cutoffs); TRUE}, error = function(e) FALSE)
      validate(need(valid, "Enter valid cutoff dates in strictly increasing order."))
    }
    assign_time_period(filter_data(dataset()$data, s), s$compare_periods, s$period_cutoffs)
  })
  auc <- auc_server("auc", filtered, reactive(input$group), reactive(input$unit))
  pairing <- paired_date_server("paired", filtered, pairing_cutoff)
  observeEvent(pairing$example(), {
    req(nrow(dataset()$data) > 0)
    updateCheckboxGroupInput(session, "sources", selected = "SKKU")
    updateSelectizeInput(session, "genotype", selected = character())
    updateSelectizeInput(session, "strain", selected = c("N2.thaw", "N2.therm"))
    updateSelectizeInput(session, "culture", selected = "20°C")
    updateSelectizeInput(session, "bacteria", selected = "OP50-1")
    updateSelectizeInput(session, "config", selected = "standard")
    updateSelectizeInput(session, "sync", selected = character())
    updateSelectizeInput(session, "runs", selected = character())
    updateDateRangeInput(session, "dates", start = min(dataset()$data$date, na.rm = TRUE), end = max(dataset()$data$date, na.rm = TRUE))
    updateSliderInput(session, "hours", value = c(2, 3.5))
    updateSelectInput(session, "group", selected = "strain")
    excluded(character())
    pairing$restore(list(dimension = "strain", reference = "N2.thaw", comparison = "N2.therm",
      cutoff = as.character(pairing_cutoff), hour = "3", same_experiment = TRUE, separate_males = TRUE, allow_unknown = FALSE, page = 1))
  }, ignoreInit = TRUE)
  decorated <- reactive({
    d <- decorate_data(filtered(), input$group, input$facet)
    if (isTRUE(input$compare_periods)) {
      d$curve <- paste(d$curve, d$time_period, sep = " · ")
      levels <- unique(d$curve[order(as.character(d[[input$group]]), d$time_period_index)])
      d$curve <- factor(d$curve, levels = levels)
    }
    d
  })
  summary <- reactive(summarise_curves(decorated(), input$unit))
  panels <- reactive(sort(unique(decorated()$panel)))
  page_panels <- reactive({
    p <- safe_page(input$panel_page, ceiling(length(panels()) / 12))
    panels()[seq_along(panels()) %in% seq((p - 1) * 12 + 1, p * 12)]
  })
  plot_object <- reactive({
    d <- decorated()
    validate(need(nrow(d) > 0, "No observations match these filters. Clear a filter or choose another data source."),
             need(length(unique(d$curve)) <= 30, "More than 30 curves selected. Narrow the genotype or strain filters, or change Color / compare."))
    colors <- setNames(grDevices::hcl.colors(length(unique(d$curve)), "Dark 3"), sort(unique(d$curve)))
    make_curve_plot(d[d$panel %in% page_panels(), , drop = FALSE], summary()[summary()$panel %in% page_panels(), , drop = FALSE], input$mode, input$uncertainty, colors)
  })
  output$curve_container <- renderUI({
    plotlyOutput("curves", height = paste0(max(570, ceiling(length(page_panels()) / 3) * 220 + 150), "px"))
  })
  output$curves <- renderPlotly({
    p <- ggplotly(plot_object(), tooltip = "text", source = "thermo")
    p <- layout(p, legend = list(orientation = "h", y = -0.16), margin = list(b = 100), hovermode = "closest")
    p <- config(p, displaylogo = FALSE, toImageButtonOptions = list(format = "svg", filename = "thermotolerance_curves"))
    event_register(p, "plotly_click")
  })
  output$metrics <- renderUI({
    d <- filtered()
    metric <- function(n, label) div(class = "metric", div(class = "metric-value", format(n, big.mark = ",")), div(class = "metric-label", label))
    div(class = "metrics", metric(nrow(d), "observations"), metric(length(unique(d$run_id)), "recorded runs"),
        metric(length(unique(d$plate_id[!d$ambiguous_plate])), "resolved plates"), metric(length(unique(d$genotype)), "genotypes"))
  })
  output$data_notice <- renderUI({
    d <- filtered(); candidate <- filter_data(dataset()$data, settings(), apply_quality = FALSE)
    notes <- character()
    if (nrow(candidate) > nrow(d)) notes <- c(notes, paste(nrow(candidate) - nrow(d), "observations omitted by quality rules or manual exclusions."))
    if (any(d$ambiguous_plate)) notes <- c(notes, paste(sum(d$ambiguous_plate), "observations have unresolved plate identity; shown as points, included in means."))
    mixed <- c("source", "culture", "bacteria", "config", "sync")
    mixed <- mixed[vapply(mixed, function(x) length(unique(d[[x]])) > 1 && !x %in% c(input$group, input$facet), logical(1))]
    if (length(mixed)) notes <- c(notes, paste("Pooled across:", paste(mixed, collapse = ", "), "— use filters or panels to separate these conditions."))
    if (isTRUE(input$compare_periods) && any(is.na(d$date))) notes <- c(notes, "Undated observations are shown separately as ‘Undated (not assigned)’; they are not placed in a dated time period.")
    if (length(notes)) div(class = "notice", paste(notes, collapse = " "))
  })
  output$panel_count <- renderText(paste(length(panels()), "panels ·", max(1, ceiling(length(panels()) / 12)), "pages"))
  output$loaded_at <- renderText(paste("Loaded", dataset()$loaded_at))
  output$excluded_count <- renderText(paste(length(excluded()), "manually excluded observations in this view."))
  output$provenance <- renderPrint(list(files = dataset()$files, md5 = dataset()$hashes, loaded = dataset()$loaded_at))
  observeEvent(list(input$facet, input$group, input$sources, input$genotype, input$strain), {
    updateNumericInput(session, "row_page", value = 1)
    selected(NULL)
  })
  observeEvent(event_data("plotly_click", source = "thermo"), {
    event <- event_data("plotly_click", source = "thermo")
    if (length(event$key)) {
      selected(as.character(event$key[1]))
      updateTabsetPanel(session, "detail_tab", selected = "Point inspector")
    }
  })
  selected_row <- reactive({
    d <- filtered()
    d[d$observation_id %in% selected(), , drop = FALSE]
  })
  output$point_detail <- renderUI({
    key <- selected(); row <- selected_row()
    if (is.null(key)) return(div(class = "empty-detail", h3("Every point has a story."), p("Click an observation to inspect its original counts, assay notes and plate time course. Click a mean point to see its summary.")))
    if (startsWith(key, "mean::")) {
      s <- summary(); keys <- paste("mean", s$panel, s$curve, s$hours, sep = "::"); s <- s[keys == key, , drop = FALSE]
      if (!nrow(s)) return(p("The selected mean is outside the current filters."))
      return(tagList(h3(paste(s$curve[1], "·", s$hours[1], "hours")), p(sprintf("Mean %.2f%% · %s observations · %s recorded runs · SE %s", s$mean[1], s$n_observations[1], s$n_runs[1], ifelse(is.na(s$se[1]), "undefined", round(s$se[1], 2))))))
    }
    if (!nrow(row)) return(p("The selected observation is excluded or outside the current filters."))
    tagList(h3(paste(row$strain, "·", row$date, "·", row$hours, "hours")),
      p(paste(row$genotype, "|", row$culture, "|", row$bacteria, "|", row$config)),
      p(sprintf("Survival %.2f%% · alive %s · dead %s · ruptured %s · suicide %s · missing %s", row$survival_pct, row$alive, row$dead, row$Rup, row$suicide, row$missing)),
      p(paste("Original strain:", row$raw_strain, "· original diet:", row$raw_bacteria)),
      p(paste("Source:", source_files[[row$source]], "· data row", row$source_row, "· experiment", row$expt, "· row", row$row)),
      p(paste("Note:", ifelse(nzchar(row$note), row$note, "—"))),
      if (row$ambiguous_plate) p(class = "notice", "Plate identity is unresolved. The table lists observations sharing this candidate identifier; they may not be one plate."))
  })
  detail_columns <- c("observation_id", "date", "expt", "row", "hours", "strain", "genotype", "survival_pct", "alive", "dead", "Rup", "suicide", "missing", "note")
  output$plate_detail <- renderTable({
    row <- selected_row(); req(nrow(row))
    d <- filtered(); d <- d[d$plate_id == row$plate_id, , drop = FALSE]
    format_table_dates(d[order(d$hours), detail_columns, drop = FALSE])
  }, digits = 2, striped = TRUE, spacing = "s", na = "—")
  observeEvent(input$exclude_point, {
    row <- selected_row()
    if (nrow(row)) excluded(unique(c(excluded(), row$observation_id))) else showNotification("Click an individual observation first.", type = "message")
  })
  observeEvent(input$clear_exclusions, excluded(character()))
  searched_rows <- reactive({
    d <- filtered(); q <- trimws(input$row_search %||% "")
    if (nzchar(q) && nrow(d)) d <- d[apply(d[detail_columns], 1, function(x) any(grepl(tolower(q), tolower(x), fixed = TRUE))), , drop = FALSE]
    d[order(d$date, d$expt, d$row, d$hours), , drop = FALSE]
  })
  observeEvent(input$row_search, updateNumericInput(session, "row_page", value = 1))
  output$row_count <- renderText(paste(nrow(searched_rows()), "matching rows ·", max(1, ceiling(nrow(searched_rows()) / 25)), "pages"))
  output$rows <- renderTable({
    d <- searched_rows(); p <- safe_page(input$row_page, ceiling(nrow(d) / 25))
    format_table_dates(d[seq_len(nrow(d)) %in% seq((p - 1) * 25 + 1, p * 25), detail_columns, drop = FALSE])
  }, digits = 2, striped = TRUE, spacing = "s", na = "—")
  output$summary_table <- renderTable(head(summary(), 100), digits = 2, striped = TRUE, spacing = "s", na = "—")
  reset_filters <- function(example) {
    d <- dataset()$data
    req(nrow(d) > 0)
    updateCheckboxGroupInput(session, "sources", selected = if (example && "SKKU" %in% names(dataset()$files)) "SKKU" else names(dataset()$files))
    for (field in c("genotype", "strain", "culture", "bacteria", "config", "sync")) {
      value <- if (example) switch(field, genotype = c("wild type", "sma-9(wk55)"), culture = "20°C", bacteria = "OP50-1", config = "standard", character()) else character()
      updateSelectizeInput(session, field, selected = value)
    }
    updateSelectizeInput(session, "runs", selected = character())
    bounds <- browser_dates(d)
    updateDateRangeInput(session, "dates", start = bounds[1], end = bounds[2])
    updateSliderInput(session, "hours", value = range(d$hours, na.rm = TRUE))
    updateCheckboxInput(session, "undated", value = !example)
    updateCheckboxInput(session, "quality", value = TRUE)
    updateCheckboxInput(session, "compare_periods", value = FALSE)
    updateDateInput(session, "period_cutoff", value = "2026-07-01")
    updateSelectInput(session, "period_count", selected = 2)
    updateDateInput(session, "period_cutoff2", value = "2026-08-01")
    updateDateInput(session, "period_cutoff3", value = "2026-09-01")
    updateNumericInput(session, "panel_page", value = 1)
    excluded(character()); selected(NULL)
  }
  observeEvent(input$defaults, reset_filters(TRUE))
  observeEvent(input$clear, reset_filters(FALSE))
  parts <- reactiveVal(list())
  output$has_data <- reactive(nrow(dataset()$data) > 0)
  outputOptions(output, "has_data", suspendWhenHidden = FALSE)
  output$file_status <- renderText({
    x <- dataset()
    if (!length(x$files)) return("Choose SKKU, JHU, or both. No experimental data is bundled with this site.")
    paste(paste(names(x$files), x$files, sep = ": "), collapse = " · ")
  })
  apply_browser_snapshot <- function(next_parts) {
    fresh <- combine_browser_sources(next_parts)
    parts(next_parts); dataset(fresh)
    excluded(character()); selected(NULL)
    d <- fresh$data
    updateCheckboxGroupInput(session, "sources", choices = setNames(names(next_parts), names(next_parts)), selected = names(next_parts))
    for (field in c("genotype", "strain", "culture", "bacteria", "config", "sync")) {
      updateSelectizeInput(session, field, choices = sort(unique(d[[field]])), selected = character())
    }
    updateSelectizeInput(session, "runs", choices = sort(unique(d$run_id)), selected = character(), server = TRUE)
    dates <- browser_dates(d); hours <- browser_hours(d)
    updateDateRangeInput(session, "dates", min = dates[1], max = dates[2], start = dates[1], end = dates[2])
    updateSliderInput(session, "hours", min = hours[1], max = hours[2], value = hours)
    updateCheckboxInput(session, "undated", value = TRUE)
    updateNumericInput(session, "panel_page", value = 1)
    updateNumericInput(session, "row_page", value = 1)
    showNotification("Files loaded. Filters and manual exclusions were reset; refine your comparison below.", type = "message")
  }
  for (source in names(source_files)) local({
    key <- source
    observeEvent(input[[paste0("csv_", key)]], {
      tryCatch({
        parsed <- read_browser_csv(input[[paste0("csv_", key)]], key)
        next_parts <- parts(); next_parts[[key]] <- parsed
        apply_browser_snapshot(next_parts)
      }, error = function(e) showNotification(paste("Could not load", key, "CSV:", conditionMessage(e)), type = "error", duration = NULL))
    }, ignoreInit = TRUE)
    observeEvent(input[[paste0("remove_", key)]], {
      next_parts <- parts(); next_parts[[key]] <- NULL
      apply_browser_snapshot(next_parts)
      session$sendCustomMessage("clearFileInput", paste0("csv_", key))
    }, ignoreInit = TRUE)
  })
  output$save_view <- downloadHandler(filename = function() paste0("thermo-view-", Sys.Date(), ".json"), content = function(file) {
    s <- settings(); ps <- pairing$settings()
    if (length(ps$reference) == 1 && length(ps$comparison) == 1 && ps$reference != ps$comparison) s$pairing <- ps
    ac <- auc$settings()
    if (length(ac$reference) == 1 && length(ac$comparison) == 1 && ac$reference != ac$comparison) s$auc <- ac
    jsonlite::write_json(list(schema_version = 1, saved_at = as.character(Sys.time()), files = as.list(dataset()$files), hashes = as.list(dataset()$hashes), settings = s), file, auto_unbox = TRUE, pretty = TRUE, null = "null")
  })
  observeEvent(input$restore_view, {
    req(nrow(dataset()$data) > 0)
    tryCatch({
      view <- jsonlite::read_json(input$restore_view$datapath, simplifyVector = TRUE)
      s <- view$settings
      period_cutoffs <- validate_period_cutoffs(unlist(s$period_cutoffs %||% s$period_cutoff %||% "2026-07-01"))
      stopifnot(identical(as.integer(view$schema_version), 1L), is.list(s), length(s$dates) == 2, length(s$hours) == 2,
        all(!is.na(as.Date(s$dates))), all(is.finite(s$hours)), s$hours[1] <= s$hours[2],
        s$group %in% unname(group_choices), s$facet %in% unname(facet_choices), s$mode %in% c("mean", "points", "replicates", "both"),
        s$unit %in% c("plate", "run"), s$uncertainty %in% c("none", "se", "sd"))
      for (field in c("genotype", "strain", "culture", "bacteria", "config", "sync", "runs")) {
        available <- if (field == "runs") sort(unique(dataset()$data$run_id)) else sort(unique(dataset()$data[[field]]))
        updateSelectizeInput(session, field, choices = union(available, s[[field]]), selected = s[[field]] %||% character(), server = field == "runs")
      }
      updateCheckboxGroupInput(session, "sources", selected = s$sources %||% character())
      updateDateRangeInput(session, "dates", start = s$dates[1], end = s$dates[2])
      updateCheckboxInput(session, "compare_periods", value = isTRUE(s$compare_periods))
      updateSelectInput(session, "period_count", selected = length(period_cutoffs) + 1L)
      updateDateInput(session, "period_cutoff", value = period_cutoffs[1])
      updateDateInput(session, "period_cutoff2", value = if (length(period_cutoffs) >= 2) period_cutoffs[2] else as.Date("2026-08-01"))
      updateDateInput(session, "period_cutoff3", value = if (length(period_cutoffs) >= 3) period_cutoffs[3] else as.Date("2026-09-01"))
      updateSliderInput(session, "hours", value = s$hours)
      for (field in c("quality", "undated")) updateCheckboxInput(session, field, value = isTRUE(s[[field]]))
      for (field in c("group", "facet", "mode", "unit", "uncertainty")) updateSelectInput(session, field, selected = s[[field]])
      updateNumericInput(session, "panel_page", value = max(1, as.integer(s$panel_page %||% 1)))
      excluded(as.character(s$excluded %||% character())); selected(NULL)
      if (is.list(s$pairing)) pairing$restore(s$pairing)
      if (is.list(s$auc)) auc$restore(s$auc)
      same <- setequal(names(unlist(view$hashes)), names(dataset()$hashes)) && identical(unname(unlist(view$hashes)[names(dataset()$hashes)]), unname(dataset()$hashes))
      if (!same) showNotification("View restored, but source fingerprints differ. Results and row-based manual exclusions may have changed; review them before use.", type = "warning", duration = NULL) else showNotification("View restored; source fingerprints match.", type = "message")
    }, error = function(e) showNotification(paste("Cannot restore this view:", conditionMessage(e)), type = "error", duration = NULL))
  })
  output$export_rows <- downloadHandler(filename = "thermotolerance_selected.csv", content = function(file) write.csv(filtered(), file, row.names = FALSE, na = ""))
  output$export_summary <- downloadHandler(filename = "thermotolerance_summary.csv", content = function(file) write.csv(summary(), file, row.names = FALSE, na = ""))
  output$plot_pdf <- downloadHandler(filename = "thermotolerance_curves.pdf", content = function(file) {
    ggsave(file, plot_object(), device = grDevices::cairo_pdf, width = 11, height = max(6, ceiling(length(page_panels()) / 3) * 2.5))
  })
  output$plot_png <- downloadHandler(filename = "thermotolerance_curves.png", content = function(file) {
    ggsave(file, plot_object(), device = "png", width = 11, height = max(6, ceiling(length(page_panels()) / 3) * 2.5), dpi = 240, bg = "white")
  })
}
shinyApp(ui, server)
